### ISSUE TITLE
execution_error

### ISSUE THREAD

**Issue by AnjaliC4** [caleblareau/bap#30]
Hi, thanks for this awesome tool.
I am getting the error at processing of the bam files
[atac.positionsort.MAPQ30.snakemake.log](https://github.com/caleblareau/bap/files/5557064/atac.positionsort.MAPQ30.snakemake.log)

:
stop_if_wrong_length("'seqnames'", ans_len) :
  'seqnames' must have the length of the object to construct (1) or
  length 1
Calls: findOverlaps ... makeGRangesFromDataFrame -> GRanges -> new_GRanges -> stop_if_wrong_length
Execution halted

I am using 10x scATAC-seq but the files are processed by another pipeline(scATAC-pro)  and not cellranger. This pipeline essentially does the same thing except the barcode flag is probably different in the bam files, so I did not specify the barcode tag. Following was my command:
bap2 bam -i ~/mapping_result/atac.positionsort.MAPQ30.bam -o ~/atac/bap -r hg38 -c 32 -w ~/atac/barcodes.txt

I have attached an entire snakemake log file with the error reported in it. Thanks for your help!

**Comment by caleblareau** [comment]
Hmmm can you show me the first few lines of the bam file? Is it in the sequencing read name rather than the sam tag?

On Nov 17, 2020, at 5:01 PM, Anjali Chawla <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi, thanks for this awesome tool.
I am getting the error at processing of the bam files
atac.positionsort.MAPQ30.snakemake.log<https://github.com/caleblareau/bap/files/5557064/atac.positionsort.MAPQ30.snakemake.log>
atac.positionsort.MAPQ30.snakemake.log<https://github.com/caleblareau/bap/files/5557065/atac.positionsort.MAPQ30.snakemake.log>

:
stop_if_wrong_length("'seqnames'", ans_len) :
'seqnames' must have the length of the object to construct (1) or
length 1
Calls: findOverlaps ... makeGRangesFromDataFrame -> GRanges -> new_GRanges -> stop_if_wrong_length
Execution halted

I am using 10x scATAC-seq but the files are processed by another pipeline(scATAC-pro) and not cellranger. This pipeline essentially does the same thing except the barcode flag is probably different in the bam files, so I did not specify the barcode tag. Following was my command:
bap2 bam -i ~/mapping_result/atac.positionsort.MAPQ30.bam -o ~/atac/bap -r hg38 -c 32 -w ~/atac/barcodes.txt

I have attached an entire snakemake log file with the error reported in it. Thanks for your help!

**Comment by AnjaliC4** [comment]
Hi, I have attached first few lines of bam file here.
[bam.txt](https://github.com/caleblareau/bap/files/5578542/bam.txt)
Please let me know what you think. Thanks

**Comment by caleblareau** [comment]
Yeah so bap doesn’t support having the barcode in the read name (sorry, I can imagine that this is annoying as other tools use it that way).

You’ll want to extract the barcode and append it as a sam tag  (see this script for inspiration but it won’t out-of-the-box work since you use the : delimiter which is used in other places— you’ll have to do something slightly custom https://github.com/caleblareau/bap/blob/master/bap/cli_reanno.py)

After you supply the bam file with a sam tag for the bead barcode, my sense is that this should just work  (e.g. CB) ]]

On Nov 21, 2020, at 2:35 PM, Anjali Chawla <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi, I have attached first few lines of bam file here.
bam.txt<https://github.com/caleblareau/bap/files/5578542/bam.txt>
Please let me know what you think. Thanks
