### ISSUE TITLE
Many barcodes failed to pass Knee filtering

### ISSUE THREAD

**Issue by esroom** [caleblareau/bap#35]
Hi, I got into trouble but have no idea about it when using bap2.
I have 8 libraries, all using the same processes, 2 libraries have few barcodes pass the Knee filtering, like this
![ATAC-4 beadBarcodeKnee](https://user-images.githubusercontent.com/44914876/124532374-fab05500-de42-11eb-969b-6d62e9a3f60e.png)
![ATAC-4 jaccardOverlapKnee](https://user-images.githubusercontent.com/44914876/124532437-27646c80-de43-11eb-9275-02de08574e83.png)
And normal libraries like this,
![ATAC-3 beadBarcodeKnee](https://user-images.githubusercontent.com/44914876/124532508-4b27b280-de43-11eb-864a-71e6ff7ae099.png)
![ATAC-3 jaccardOverlapKnee](https://user-images.githubusercontent.com/44914876/124532520-4e22a300-de43-11eb-997c-d48444f506b3.png)
I wondered what may cause this problem? Bad libraries or should I change some parameters (I used default parameters)?

**Comment by caleblareau** [comment]
there's not a super clean knee, which could be caused by a bad library quality or any number of things... 

The path of least resistance would be to set a hard-coded threshold of say 500 (`-bf 500` in the execution) to keep all bead barcodes with at least that many reads and then do more downstream filtering
